# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_s00_regslice_32/base_s00_regslice_32.xci
# IP: The module: 'base_s00_regslice_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_s00_regslice_32/base_s00_regslice_32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_s00_regslice_32/base_s00_regslice_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_s00_regslice_32/base_s00_regslice_32.xci
# IP: The module: 'base_s00_regslice_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_s00_regslice_32/base_s00_regslice_32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_s00_regslice_32/base_s00_regslice_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
