# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_m03_regslice_30/base_m03_regslice_30.xci
# IP: The module: 'base_m03_regslice_30' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_m03_regslice_30/base_m03_regslice_30_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m03_regslice_30'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_m03_regslice_30/base_m03_regslice_30_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m03_regslice_30'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_m03_regslice_30/base_m03_regslice_30.xci
# IP: The module: 'base_m03_regslice_30' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_m03_regslice_30/base_m03_regslice_30_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m03_regslice_30'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/osher/Vivado_Projects/AXIS_SOBEL_BD3/AXIS_SOBEL_BD3.srcs/sources_1/bd/base/ip/base_m03_regslice_30/base_m03_regslice_30_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m03_regslice_30'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
