# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_7/base_xbar_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_7 || ORIG_REF_NAME==base_xbar_7} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph1_0/base_ps7_0_axi_periph1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph1_0 || ORIG_REF_NAME==base_ps7_0_axi_periph1_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/base/ip/base_system_interrupts_0/base_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_interrupts_0 || ORIG_REF_NAME==base_system_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_9/base_xbar_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_9 || ORIG_REF_NAME==base_xbar_9} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_0_1/base_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_interconnect_0_1 || ORIG_REF_NAME==base_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/base/ip/base_xbar_10/base_xbar_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_10 || ORIG_REF_NAME==base_xbar_10} -quiet] -quiet

# IP: bd/base/ip/base_axi_mem_intercon_1/base_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_1 || ORIG_REF_NAME==base_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0/base_axi_vdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0 || ORIG_REF_NAME==base_axi_vdma_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_register_slice_0_0/base_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_register_slice_0_0 || ORIG_REF_NAME==base_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/base/ip/base_color_convert_0/base_color_convert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_color_convert_0 || ORIG_REF_NAME==base_color_convert_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_gpio_hdmiin_0 || ORIG_REF_NAME==base_axi_gpio_hdmiin_0} -quiet] -quiet

# IP: bd/base/ip/base_color_swap_0_0/base_color_swap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_color_swap_0_0 || ORIG_REF_NAME==base_color_swap_0_0} -quiet] -quiet

# IP: bd/base/ip/base_dvi2rgb_0_0/base_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_dvi2rgb_0_0 || ORIG_REF_NAME==base_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==base_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/base/ip/base_vtc_in_0/base_vtc_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_vtc_in_0 || ORIG_REF_NAME==base_vtc_in_0} -quiet] -quiet

# IP: bd/base/ip/base_pixel_pack_0/base_pixel_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pixel_pack_0 || ORIG_REF_NAME==base_pixel_pack_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_register_slice_0_1/base_axis_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_register_slice_0_1 || ORIG_REF_NAME==base_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/base/ip/base_color_convert_1/base_color_convert_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_color_convert_1 || ORIG_REF_NAME==base_color_convert_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_dynclk_0/base_axi_dynclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dynclk_0 || ORIG_REF_NAME==base_axi_dynclk_0} -quiet] -quiet

# IP: bd/base/ip/base_color_swap_0_1/base_color_swap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_color_swap_0_1 || ORIG_REF_NAME==base_color_swap_0_1} -quiet] -quiet

# IP: bd/base/ip/base_hdmi_out_hpd_video_0/base_hdmi_out_hpd_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_hdmi_out_hpd_video_0 || ORIG_REF_NAME==base_hdmi_out_hpd_video_0} -quiet] -quiet

# IP: bd/base/ip/base_rgb2dvi_0_0/base_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rgb2dvi_0_0 || ORIG_REF_NAME==base_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==base_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/base/ip/base_vtc_out_0/base_vtc_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_vtc_out_0 || ORIG_REF_NAME==base_vtc_out_0} -quiet] -quiet

# IP: bd/base/ip/base_pixel_unpack_0/base_pixel_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_pixel_unpack_0 || ORIG_REF_NAME==base_pixel_unpack_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_pixelclk_0/base_proc_sys_reset_pixelclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==base_proc_sys_reset_pixelclk_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_0/base_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_0 || ORIG_REF_NAME==base_xlconcat_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_dma_0_2/base_axi_dma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dma_0_2 || ORIG_REF_NAME==base_axi_dma_0_2} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_2/base_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_2 || ORIG_REF_NAME==base_xlconcat_0_2} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_0_0/base_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_0_0 || ORIG_REF_NAME==base_smartconnect_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_3/base_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_3 || ORIG_REF_NAME==base_xlconcat_0_3} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_38/base_s00_regslice_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_38 || ORIG_REF_NAME==base_s00_regslice_38} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_2/base_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_2 || ORIG_REF_NAME==base_auto_pc_2} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_38/base_m00_regslice_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_38 || ORIG_REF_NAME==base_m00_regslice_38} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_38/base_m01_regslice_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_38 || ORIG_REF_NAME==base_m01_regslice_38} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_38/base_m02_regslice_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_38 || ORIG_REF_NAME==base_m02_regslice_38} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_39/base_s00_regslice_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_39 || ORIG_REF_NAME==base_s00_regslice_39} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_3/base_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_3 || ORIG_REF_NAME==base_auto_pc_3} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_39/base_m00_regslice_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m00_regslice_39 || ORIG_REF_NAME==base_m00_regslice_39} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_39/base_m01_regslice_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m01_regslice_39 || ORIG_REF_NAME==base_m01_regslice_39} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_0/base_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_cc_0 || ORIG_REF_NAME==base_auto_cc_0} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_39/base_m02_regslice_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m02_regslice_39 || ORIG_REF_NAME==base_m02_regslice_39} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_1/base_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_cc_1 || ORIG_REF_NAME==base_auto_cc_1} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_0/base_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m03_regslice_0 || ORIG_REF_NAME==base_m03_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_0/base_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m04_regslice_0 || ORIG_REF_NAME==base_m04_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_0/base_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m05_regslice_0 || ORIG_REF_NAME==base_m05_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_0/base_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m06_regslice_0 || ORIG_REF_NAME==base_m06_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_2/base_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_cc_2 || ORIG_REF_NAME==base_auto_cc_2} -quiet] -quiet

# IP: bd/base/ip/base_m07_regslice_0/base_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m07_regslice_0 || ORIG_REF_NAME==base_m07_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_3/base_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_cc_3 || ORIG_REF_NAME==base_auto_cc_3} -quiet] -quiet

# IP: bd/base/ip/base_m08_regslice_0/base_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m08_regslice_0 || ORIG_REF_NAME==base_m08_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_m09_regslice_0/base_m09_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_m09_regslice_0 || ORIG_REF_NAME==base_m09_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_us_0/base_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_4 || ORIG_REF_NAME==base_auto_pc_4} -quiet] -quiet

# IP: bd/base/ip/base_axis_gaussian_0_0/base_axis_gaussian_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_gaussian_0_0 || ORIG_REF_NAME==base_axis_gaussian_0_0} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
